CREATE TABLE users (
    userId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    nickname VARCHAR(255) NOT NULL,
    profileImage VARCHAR(500),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deletedAt TIMESTAMP
);

CREATE TABLE posts (
    postId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    postBody TEXT NOT NULL,
    postImage VARCHAR(500),
    likes INT NOT NULL DEFAULT 0,
    views INT NOT NULL DEFAULT 0,
    comments INT NOT NULL DEFAULT 0,
    edited BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    blinded BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    deletedAt TIMESTAMP,
    userId BIGINT NOT NULL,
    CONSTRAINT fk_posts_user FOREIGN KEY (userId) REFERENCES users(userId)
);

CREATE TABLE comments (
    commentId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commentBody TEXT NOT NULL,
    edited BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    deletedAt TIMESTAMP,
    postId BIGINT NOT NULL,
    userId BIGINT NOT NULL,
    parentCommentId BIGINT,
    CONSTRAINT fk_comments_post FOREIGN KEY (postId) REFERENCES posts(postId),
    CONSTRAINT fk_comments_user FOREIGN KEY (userId) REFERENCES users(userId),
    CONSTRAINT fk_comments_parent FOREIGN KEY (parentCommentId) REFERENCES comments(commentId)
);

CREATE TABLE drafts (
    draftId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    postBody TEXT,
    postImage VARCHAR(500),
    published BOOLEAN NOT NULL DEFAULT FALSE,
    updateAt TIMESTAMP,
    userId BIGINT NOT NULL,
    CONSTRAINT fk_drafts_user FOREIGN KEY (userId) REFERENCES users(userId)
);

CREATE TABLE postEditHistory (
    historyId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postId BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    postBody TEXT NOT NULL,
    postImage VARCHAR(500),
    createdAt TIMESTAMP NOT NULL,
    CONSTRAINT fk_post_edit_history_post FOREIGN KEY (postId) REFERENCES posts(postId)
);

CREATE TABLE postLikes (
    postLikeId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    postId BIGINT NOT NULL,
    CONSTRAINT fk_post_likes_user FOREIGN KEY (userId) REFERENCES users(userId),
    CONSTRAINT fk_post_likes_post FOREIGN KEY (postId) REFERENCES posts(postId),
    CONSTRAINT uq_post_likes_user_post UNIQUE (userId, postId)
);

CREATE TABLE postReports (
    reportId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason VARCHAR(1000) NOT NULL,
    reportedAt TIMESTAMP NOT NULL,
    postId BIGINT NOT NULL,
    userId BIGINT NOT NULL,
    CONSTRAINT fk_post_reports_post FOREIGN KEY (postId) REFERENCES posts(postId),
    CONSTRAINT fk_post_reports_user FOREIGN KEY (userId) REFERENCES users(userId),
    CONSTRAINT uq_post_reports_user_post UNIQUE (userId, postId)
);

CREATE TABLE postViews (
    postViewId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewedAt TIMESTAMP NOT NULL,
    postId BIGINT NOT NULL,
    userId BIGINT NOT NULL,
    CONSTRAINT fk_post_views_post FOREIGN KEY (postId) REFERENCES posts(postId),
    CONSTRAINT fk_post_views_user FOREIGN KEY (userId) REFERENCES users(userId),
    CONSTRAINT uq_post_views_user_post UNIQUE (userId, postId)
);
